server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: books_service
          uri: lb://books-service
          predicates:
            - Path=/books/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

